const DEFAULTS={repo:'PierreAccolite/the-square-table',projectPath:'projects/square-table-ui',pagesUrl:'https://pierreaccolite.github.io/the-square-table/',gptUrl:'',grokUrl:'',pollMinutes:2,githubToken:''};
const getSettings=async()=>Object.assign({},DEFAULTS,await chrome.storage.local.get(DEFAULTS));
async function api(path){const s=await getSettings(),h={Accept:'application/vnd.github+json'};if(s.githubToken)h.Authorization=`Bearer ${s.githubToken}`;const r=await fetch(`https://api.github.com/repos/${s.repo}/contents/${path}?ref=main`,{headers:h,cache:'no-store'});if(!r.ok)throw new Error(`GitHub ${r.status}`);return r.json()}
async function raw(path){const s=await getSettings();const r=await fetch(`https://raw.githubusercontent.com/${s.repo}/main/${path}`,{cache:'no-store'});if(!r.ok)throw new Error(`Raw ${r.status}`);return r.text()}
function meta(t,k){const m=t.match(new RegExp(`\\*\\*${k}:\\*\\*\\s*(.+)`,'i'));return m?m[1].trim():'—'}
async function poll(){try{const s=await getSettings();const files=(await api(`${s.projectPath}/messages`)).filter(x=>x.type==='file'&&x.name.endsWith('.md')).sort((a,b)=>b.name.localeCompare(a.name));const state=await chrome.storage.local.get({seenShas:[],latestMessages:[]});const seen=new Set(state.seenShas||[]),latest=[];let unread=0;for(const f of files.slice(0,8)){const text=await raw(f.path);const rec={name:f.name,path:f.path,sha:f.sha,from:meta(text,'From'),to:meta(text,'To'),type:meta(text,'Type')};latest.push(rec);if(!seen.has(f.sha))unread++}await chrome.storage.local.set({latestMessages:latest,lastPoll:Date.now(),lastError:'',unreadCount:unread});await chrome.action.setBadgeText({text:unread?String(Math.min(unread,99)):''});await chrome.action.setBadgeBackgroundColor({color:'#d6a94d'})}catch(e){await chrome.storage.local.set({lastError:e.message,lastPoll:Date.now()});await chrome.action.setBadgeText({text:'!'})}}
async function installAlarm(){const s=await getSettings();await chrome.alarms.clear('squareTablePoll');chrome.alarms.create('squareTablePoll',{periodInMinutes:Math.max(1,Number(s.pollMinutes)||2)})}
async function focusOrOpen(url,patterns){let tabs=[];for(const pattern of patterns){const found=await chrome.tabs.query({url:pattern});tabs.push(...found)}if(url){const exact=await chrome.tabs.query({url});tabs.push(...exact)}const unique=[...new Map(tabs.map(t=>[t.id,t])).values()];const tab=unique[0];if(tab){await chrome.tabs.update(tab.id,{active:true});if(tab.windowId!=null)await chrome.windows.update(tab.windowId,{focused:true});return {reused:true}}if(url){await chrome.tabs.create({url});return {reused:false}}return {reused:false,error:'URL not configured'}}
chrome.runtime.onInstalled.addListener(async()=>{await installAlarm();await poll()});
chrome.runtime.onStartup.addListener(async()=>{await installAlarm();await poll()});
chrome.alarms.onAlarm.addListener(a=>{if(a.name==='squareTablePoll')poll()});
chrome.storage.onChanged.addListener((changes,area)=>{if(area==='local'&&(changes.pollMinutes||changes.repo||changes.projectPath||changes.githubToken)){installAlarm();poll()}});
chrome.runtime.onMessage.addListener((msg,_sender,send)=>{(async()=>{const s=await getSettings();if(msg.type==='poll')return poll();if(msg.type==='markRead'){const st=await chrome.storage.local.get({latestMessages:[]});await chrome.storage.local.set({seenShas:(st.latestMessages||[]).map(x=>x.sha),unreadCount:0});await chrome.action.setBadgeText({text:''});return}if(msg.type==='open'){const map={square:{url:s.pagesUrl,p:['https://pierreaccolite.github.io/the-square-table/*']},gpt:{url:s.gptUrl,p:['https://chatgpt.com/*']},grok:{url:s.grokUrl,p:['https://grok.com/*']},github:{url:`https://github.com/${s.repo}/tree/main/${s.projectPath}`,p:[`https://github.com/${s.repo}/*`]}};const t=map[msg.target];if(t)return focusOrOpen(t.url,t.p)}})().then(send).catch(e=>send({error:e.message}));return true});
